---
name: Deploy Linux scripts

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

# # # ? Start the job on all push 
on:
  push:
  pull_request:
    branches: [master, main]

# # # ? Set the Job 

jobs:
  lint_code:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

# # # ? Run Linter against code base 
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4    # # #* https://github.com/github/super-linter#slim-image
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# # # ? Create a k3d cluster 
      - name: Deploy linux scripts
        run: linux/k3d_prepare.sh
        shell: bash  

# # # ? Verify the cluster 
      - name: Verify cluster
        run: |
          kubectl cluster-info
