---
name: Gitops K8s

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

# # # ? Start the job on all push 
on:
  push:
  pull_request:
    branches: [master, main]

# # # ? Set the Job 

jobs:
  build:
    name: Prepare and test on a k3d cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

# # # ? Run Linter against code base 
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4    # # #* https://github.com/github/super-linter#slim-image
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas

# # # ? Update scripts permissions
      - name: Make scripts executable
        run: find linux/ -type f -iname "*.sh" -exec chmod +x {} \;

# # # ? Create a k3d cluster 
      - name: Run k3d_prepare.sh
        run: linux/k3d_prepare.sh
        shell: bash  

# # # ? Verify the cluster 
      - name: Verify cluster
        run: |
          kubectl cluster-info
          kubectl get nodes
